import { StyleSheet
} from "react-native";
import { Color, FontFamily, Border, Padding, FontSize } from "../../GlobalStyles";
export const StyleCMZ = StyleSheet.create({
  
    iconLayout: {
      width: "100%",
      overflow: "hidden",
      },
      parentFlexBox1: {
        alignItems: "center",
        flexDirection: "row",
      },
      iconoutlinedotsSpaceBlock: {
        display: "none",
        marginLeft: 8,
        overflow: "hidden",
      },
      buttonTypo: {
        color: Color.customTextTooltips,
        fontFamily: FontFamily.interSemiboldItalic,
        fontStyle: "italic",
        textAlign: "center",
        marginLeft: 8,
        display: "none",
        fontWeight: "600",
      },
      cardLayout: {
        width: 366,
        left: 12,
        borderRadius: Border.br_xs,
        position: "relative",
      },
      cardSpaceBlock1: {
        paddingVertical: Padding.p_base,
        paddingHorizontal: 0,
        backgroundColor: Color.gray_100,
      },
      parentFlexBox: {
        justifyContent: "space-between",
        alignItems: "center",
        flexDirection: "row",
      },
      nStandTypo: {
        color: Color.steelblue,
        fontFamily: FontFamily.notoSansMalayalamUIBold,
        fontWeight: "700",
        fontSize: FontSize.fontSansTextBaseSemibold_size,
      },
      shareFlexBox: {
        marginLeft: 20,
        alignItems: "center",
        flexDirection: "row",
      },
      cardHeader1Position: {
        zIndex: 0,
        alignSelf: "stretch",
        overflow: "hidden",
      },
      childLayout: {
        height: 186,
        width: 350,
        borderColor: "#fff",
        borderWidth: 2,
        borderStyle: "solid",
        position: "absolute",
      },
      cardSpaceBlock: {
        paddingVertical: Padding.p_6xl,
        paddingHorizontal: 0,
        justifyContent: "center",
        alignSelf: "stretch",
        overflow: "hidden",
      },
      abstractTypo: {
        fontFamily: FontFamily.interMedium,
        fontWeight: "500",
        textTransform: "lowercase",
        lineHeight: 20,
        fontSize: FontSize.fontSansTextSmSemibold_size,
        textAlign: "left",
      },
      tagdarkenFlexBox1: {
        paddingVertical: Padding.p_9xs,
        paddingHorizontal: Padding.p_xs,
        backgroundColor: Color.dodgerblue_100,
        borderRadius: Border.br_13xl,
        justifyContent: "center",
        alignItems: "center",
        flexDirection: "row",
        overflow: "hidden",
      },
      thereSpaceBlock: {
        marginTop: 18,
        alignSelf: "stretch",
      },
      unsplash9bx5vfkxytiIconLayout: {
        height: 200,
        maxWidth: "100%",
        width: "100%",
      },
      cardFlexBox: {
        paddingVertical: Padding.p_xl,
        paddingHorizontal: Padding.p_sm,
        height: 42,
        backgroundColor: Color.aliceblue,
        display: "none",
        alignSelf: "stretch",
        alignItems: "center",
        flexDirection: "row",
        overflow: "hidden",
      },
      tagdarkenFlexBox: {
        backgroundColor: Color.lavender,
        paddingVertical: Padding.p_9xs,
        paddingHorizontal: Padding.p_xs,
        borderRadius: Border.br_13xl,
        justifyContent: "center",
        alignItems: "center",
        flexDirection: "row",
        overflow: "hidden",
      },
      menuAlt2OutlineIconOverlay: {
        flex: 1,
        alignItems: "flex-start",
        justifyContent: "center",
        backgroundColor: "rgba(113, 113, 113, 0.3)",
      },
      menuAlt2OutlineIconBg: {
        position: "absolute",
        width: "100%",
        height: "100%",
        left: 0,
        top: 0,
      },
      icon: {
        height: "100%",
        overflow: "hidden",
      },
      menualt2outline: {
        height: 32,
        width: 32,
      },
      stands: {
        fontSize: FontSize.size_5xl,
        display: "flex",
        marginLeft: 18,
        textAlign: "left",
        color: Color.bluePrimary,
        fontFamily: FontFamily.notoSansMalayalamUISemibold,
        fontWeight: "600",
        alignSelf: "stretch",
        alignItems: "center",
        flex: 1,
      },
      iconsdarkfilter: {
        maxHeight: "100%",
        maxWidth: "100%",
        alignSelf: "stretch",
        overflow: "hidden",
        width: "100%",
        flex: 1,
      },
      iconoutlinedotsCircleHoriz: {
        width: 20,
        marginLeft: 8,
        height: 20,
      },
      iconoutlinedotsCircleHoriz1: {
        height: 16,
        width: 16,
        marginLeft: 8,
      },
      button: {
        fontSize: FontSize.fontSansTextXsSemibold_size,
        lineHeight: 16,
        textAlign: "center",
      },
      button1: {
        lineHeight: 20,
        fontSize: FontSize.fontSansTextSmSemibold_size,
        textAlign: "center",
        color: Color.customTextTooltips,
        fontFamily: FontFamily.interSemiboldItalic,
        fontStyle: "italic",
        marginLeft: 8,
        display: "none",
        fontWeight: "600",
      },
      button2: {
        lineHeight: 24,
        fontSize: FontSize.fontSansTextBaseSemibold_size,
        textAlign: "center",
        color: Color.customTextTooltips,
        fontFamily: FontFamily.interSemiboldItalic,
        fontStyle: "italic",
        marginLeft: 8,
        display: "none",
        fontWeight: "600",
      },
      button3: {
        fontSize: FontSize.fontSansTextLgSemibold_size,
        lineHeight: 28,
        textAlign: "center",
      },
      iconoutlinedotsCircleHoriz4: {
        width: 24,
        height: 24,
        marginLeft: 8,
      },
      buttondarken: {
        backgroundColor: Color.gray_300,
        borderColor: "#0084fa",
        height: 30,
        justifyContent: "center",
        borderWidth: 2,
        borderStyle: "solid",
        borderRadius: Border.br_xs,
        padding: Padding.p_7xs,
        width: 32,
        alignItems: "center",
        flexDirection: "row",
      },
      searchoutline: {
        padding: Padding.p_7xs,
        marginLeft: 18,
        alignItems: "center",
        flexDirection: "row",
        overflow: "hidden",
      },
      menualt2outlineParent: {
        top: 1,
        width: 390,
        height: 72,
        padding: Padding.p_xs,
        left: 0,
        position: "absolute",
        alignItems: "center",
      },
      standsCmzChild: {
        top: 72,
        borderColor: "rgba(0, 132, 250, 0.5)",
        width: 391,
        height: 1,
        borderTopWidth: 1,
        borderStyle: "solid",
        left: 0,
        position: "absolute",
      },
      standsCmzItem: {
        top: 0,
        marginTop:3,
        borderColor: "rgba(0, 132, 250, 0.65)",
        width: 391,
        left: 0,
        height: 1,
        borderTopWidth: 2,
        borderStyle: "solid",
        flex:1
      },
      text1: {
        fontSize: FontSize.size_mini,
        fontFamily: FontFamily.notoSansMalayalamUIBold,
        fontWeight: "700",
      },
      text2: {
        fontSize: FontSize.fontSansTextSmSemibold_size,
        fontFamily: FontFamily.notoSansMalayalamUISemibold,
        fontWeight: "600",
      },
      text: {
        letterSpacing: 1,
        lineHeight: 20,
        textAlign: "left",
        color: Color.bluePrimary,
      },
      likes: {
        overflow: "hidden",
      },
      loremIpsum: {
        fontSize: FontSize.size_9xl,
        color: Color.white,
        textAlign: "left",
        fontFamily: FontFamily.notoSansMalayalamUISemibold,
        fontWeight: "600",
        flex: 1,
      },
      vectorIcon: {
        width: 16,
        height: 20,
      },
      bookmark: {
        width: 65,
        height: 50,
        paddingHorizontal: Padding.p_8xs,
        paddingVertical: Padding.p_10xs,
        borderRadius: Border.br_31xl,
        justifyContent: "center",
        alignItems: "center",
        flexDirection: "row",
        overflow: "hidden",
      },
      loremIpsumParent: {
        alignSelf: "stretch",
      },
      cardHeader: {
        alignSelf: "stretch",
        overflow: "hidden",
      },
      vectorIcon1: {
        width: 15,
        height: 18,
      },
      mapShadowBox: {
        padding: Padding.p_xl,
        shadowOpacity: 1,
        elevation: 7,
        shadowRadius: 7,
        shadowOffset: {
          width: 0,
          height: 2,
        },
        shadowColor: "rgba(0, 0, 0, 0.11)",
        borderRadius: Border.br_81xl,
        height: 40,
        width: 40,
        justifyContent: "center",
        alignItems: "center",
        flexDirection: "row",
        overflow: "hidden",
      },
      nStand: {
        marginLeft: 5,
        lineHeight: 23,
        color: Color.steelblue,
        letterSpacing: 1,
        textAlign: "left",
      },
      liensDuStands: {
        textAlign: "center",
      },
      vectorIcon2: {
        width: 19,
        height: 20,
      },
      share1: {
        padding: Padding.p_3xs,
        height: 40,
        width: 40,
        borderRadius: Border.br_31xl,
        justifyContent: "center",
        alignItems: "center",
        flexDirection: "row",
        overflow: "hidden",
      },
      share: {
        overflow: "hidden",
      },
      unsplash9bx5vfkxytiIcon: {
        height: 200,
        maxWidth: "100%",
        width: "100%",
      },
      frameChild: {
        top: 7,
        left: 8,
        zIndex: 1,
      },
      unsplash9bx5vfkxytiParent: {
        alignSelf: "stretch",
      },
      abstract: {
        color: Color.white,
      },
      tagdarken1: {
        marginLeft: 8,
      },
      tagdarkenParent: {
        alignSelf: "stretch",
        flexDirection: "row",
      },
      thereAreMany: {
        height: 45,
        marginTop: 18,
        fontFamily: FontFamily.notoSansMalayalamUIRegular,
        lineHeight: 23,
        letterSpacing: 1,
        fontSize: FontSize.fontSansTextBaseSemibold_size,
        textAlign: "left",
        overflow: "hidden",
        color: Color.white,
      },
      iconsexternallink: {
        width: 11,
        height: 11,
        overflow: "hidden",
      },
      visiterLeSite: {
        marginLeft: 6,
        fontFamily: FontFamily.notoSansMalayalamUIRegular,
        lineHeight: 23,
        fontSize: FontSize.fontSansTextSmSemibold_size,
        textAlign: "left",
        color: Color.bluePrimary,
      },
      shareoutlineIcon: {
        width: 12,
        height: 12,
        overflow: "hidden",
      },
      frameParent: {
        justifyContent: "space-between",
        alignItems: "center",
        flexDirection: "row",
      },
      cardFooter: {
        backgroundColor: Color.gray_100,
        paddingVertical: Padding.p_6xl,
      },
      card: {
        top: 89,
        backgroundColor: Color.dodgerblue_200,
      },
      cardHeader1: {
        paddingVertical: Padding.p_base,
        paddingHorizontal: 0,
        backgroundColor: Color.gray_100,
      },
      unsplash9bx5vfkxytiIcon1: {
        zIndex: 1,
        alignSelf: "stretch",
        overflow: "hidden",
      },
      cardCaption1: {
        zIndex: 2,
      },
      abstract1: {
        color: Color.bluePrimary,
        fontFamily: FontFamily.interMedium,
        fontWeight: "500",
        textTransform: "lowercase",
      },
      tagdarken4: {
        marginLeft: 8,
      },
      thereAreMany1: {
        color: Color.defaultGray500,
        height: 45,
        marginTop: 18,
        fontFamily: FontFamily.notoSansMalayalamUIRegular,
        lineHeight: 23,
        letterSpacing: 1,
        fontSize: FontSize.fontSansTextBaseSemibold_size,
        textAlign: "left",
        overflow: "hidden",
      },
      cardFooter1: {
        backgroundColor: Color.white,
        zIndex: 3,
      },
      cardChild: {
        top: 111,
        left: 7,
        zIndex: 4,
      },
      card1: {
        top: 593,
        backgroundColor: Color.dodgerblue_300,
      },
      standsCmz: {
        height:"100%",
        flex: 1,
        width: "100%",
        backgroundColor: Color.gray_100,
      },
    });
  
export const StyleNancy = StyleSheet.create({
    iconLayout: {
      width: "100%",
      overflow: "hidden",
    },
    standsLayout: {
      height: 1,
      borderTopWidth: 1,
      borderStyle: "solid",
    },
    cardLayout: {
      width: 366,
      borderRadius: Border.br_xs,
      left: 12,
      position: "relative",
    },
    cardSpaceBlock4: {
      paddingVertical: Padding.p_base,
      paddingHorizontal: 0,
      backgroundColor: Color.gray_100,
    },
    textFlexBox: {
      letterSpacing: 1,
      textAlign: "left",
      lineHeight: 20,
    },
    text2Typo: {
      fontFamily: FontFamily.notoSansMalayalamUISemibold,
      fontWeight: "600",
    },
    parentFlexBox: {
      justifyContent: "space-between",
      alignItems: "center",
      flexDirection: "row",
    },
    cardCommon: {
      display: "none",
      overflow: "hidden",
    },
    shareFlexBox: {
      marginLeft: 20,
      alignItems: "center",
      flexDirection: "row",
    },
    cardHeader1Position: {
      zIndex: 0,
      alignSelf: "stretch",
      overflow: "hidden",
    },
    childLayout: {
      height: 186,
      width: 350,
      borderColor: "#fff",
      borderWidth: 2,
      borderStyle: "solid",
      position: "absolute",
    },
    cardSpaceBlock: {
      paddingVertical: Padding.p_6xl,
      justifyContent: "center",
      paddingHorizontal: 0,
      alignSelf: "stretch",
      overflow: "hidden",
    },
    abstractTypo: {
      fontFamily: FontFamily.interMedium,
      fontWeight: "500",
      textTransform: "lowercase",
      fontSize: FontSize.fontSansTextSmSemibold_size,
      textAlign: "left",
      lineHeight: 20,
    },
    tagdarkenFlexBox1: {
      paddingVertical: Padding.p_9xs,
      paddingHorizontal: Padding.p_xs,
      backgroundColor: Color.mediumvioletred_400,
      borderRadius: Border.br_13xl,
      justifyContent: "center",
      alignItems: "center",
      flexDirection: "row",
      overflow: "hidden",
    },
    thereSpaceBlock: {
      marginTop: 18,
      alignSelf: "stretch",
    },
    visiterTypo: {
      marginLeft: 6,
      fontFamily: FontFamily.notoSansMalayalamUIRegular,
      lineHeight: 23,
      fontSize: FontSize.fontSansTextSmSemibold_size,
      textAlign: "left",
    },
    unsplash9bx5vfkxytiIconLayout: {
      height: 200,
      maxWidth: "100%",
      width: "100%",
    },
    tagdarkenFlexBox: {
      backgroundColor: Color.lavender,
      paddingVertical: Padding.p_9xs,
      paddingHorizontal: Padding.p_xs,
      borderRadius: Border.br_13xl,
      justifyContent: "center",
      alignItems: "center",
      flexDirection: "row",
      overflow: "hidden",
    },
    standsNancyItemPosition: {
      left: 0,
      position: "absolute",
    },
    buttondarkenFlexBox: {
      padding: Padding.p_7xs,
      alignItems: "center",
      flexDirection: "row",
    },
    buttonTypo: {
      color: Color.customTextTooltips,
      fontFamily: FontFamily.interSemiboldItalic,
      fontStyle: "italic",
      marginLeft: 8,
      textAlign: "center",
      display: "none",
      fontWeight: "600",
    },
    standsNancyChild: {
      top: 0,
      borderColor: "rgba(248, 110, 194, 0.65)",
      width: 392,
      left: 0,
      position: "relative",
      borderTopWidth: 1,
      borderStyle: "solid",
    },
    text1: {
      fontSize: FontSize.size_mini,
      fontFamily: FontFamily.notoSansMalayalamUIBold,
      fontWeight: "700",
    },
    text2: {
      fontSize: FontSize.fontSansTextSmSemibold_size,
    },
    text: {
      color: "#f143a9",
      textAlign: "left",
      lineHeight: 20,
    },
    likes: {
      alignItems: "center",
      flexDirection: "row",
      overflow: "hidden",
    },
    loremIpsum: {
      fontSize: FontSize.size_9xl,
      color: Color.white,
      textAlign: "left",
      flex: 1,
    },
    vectorIcon: {
      height: 20,
      width: 16,
    },
    bookmark: {
      width: 65,
      height: 50,
      paddingHorizontal: Padding.p_8xs,
      paddingVertical: Padding.p_10xs,
      justifyContent: "center",
      borderRadius: Border.br_31xl,
      alignItems: "center",
      flexDirection: "row",
      overflow: "hidden",
    },
    loremIpsumParent: {
      alignSelf: "stretch",
    },
    cardHeader: {
      alignSelf: "stretch",
      overflow: "hidden",
    },
    vectorIcon1: {
      width: 15,
      height: 18,
    },
    mapShadowBox: {
      padding: Padding.p_xl,
      shadowOpacity: 1,
      elevation: 7,
      shadowRadius: 7,
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowColor: "rgba(0, 0, 0, 0.11)",
      borderRadius: Border.br_81xl,
      height: 40,
      width: 40,
      justifyContent: "center",
      alignItems: "center",
      flexDirection: "row",
      overflow: "hidden",
    },
    nStand: {
      marginLeft: 5,
      color: Color.steelblue,
      lineHeight: 23,
      fontSize: FontSize.fontSansTextBaseSemibold_size,
      fontFamily: FontFamily.notoSansMalayalamUIBold,
      fontWeight: "700",
      textAlign: "left",
      letterSpacing: 1,
    },
    liensDuStands: {
      textAlign: "center",
      color: Color.steelblue,
      fontSize: FontSize.fontSansTextBaseSemibold_size,
      fontFamily: FontFamily.notoSansMalayalamUIBold,
      fontWeight: "700",
    },
    vectorIcon2: {
      width: 19,
      height: 20,
    },
    share1: {
      padding: Padding.p_3xs,
      height: 40,
      width: 40,
      justifyContent: "center",
      borderRadius: Border.br_31xl,
      alignItems: "center",
      flexDirection: "row",
      overflow: "hidden",
    },
    share: {
      overflow: "hidden",
    },
    cardCaption: {
      paddingVertical: Padding.p_xl,
      paddingHorizontal: Padding.p_sm,
      height: 42,
      backgroundColor: Color.aliceblue,
      display: "none",
      alignItems: "center",
      flexDirection: "row",
      alignSelf: "stretch",
    },
    unsplash9bx5vfkxytiIcon: {
      height: 200,
      maxWidth: "100%",
      width: "100%",
    },
    frameChild: {
      top: 7,
      left: 8,
      zIndex: 1,
    },
    unsplash9bx5vfkxytiParent: {
      alignSelf: "stretch",
    },
    abstract: {
      color: Color.white,
    },
    tagdarken1: {
      marginLeft: 8,
    },
    tagdarkenParent: {
      flexDirection: "row",
      alignSelf: "stretch",
    },
    thereAreMany: {
      height: 45,
      fontFamily: FontFamily.notoSansMalayalamUIRegular,
      marginTop: 18,
      lineHeight: 23,
      fontSize: FontSize.fontSansTextBaseSemibold_size,
      textAlign: "left",
      letterSpacing: 1,
      overflow: "hidden",
      color: Color.white,
    },
    iconsexternallink: {
      width: 11,
      height: 11,
      overflow: "hidden",
    },
    visiterLeSite: {
      color: Color.mediumvioletred_200,
    },
    iconsexternallinkParent: {
      alignItems: "center",
      flexDirection: "row",
    },
    shareoutlineIcon: {
      width: 12,
      height: 12,
      overflow: "hidden",
    },
    frameParent: {
      justifyContent: "space-between",
      alignItems: "center",
      flexDirection: "row",
    },
    cardFooter: {
      backgroundColor: Color.gray_100,
    },
    card: {
      top: 89,
      backgroundColor: Color.dodgerblue_200,
    },
    text3: {
      color: Color.mediumvioletred_200,
      textAlign: "left",
      lineHeight: 20,
    },
    cardHeader1: {
      paddingVertical: Padding.p_base,
      paddingHorizontal: 0,
      backgroundColor: Color.gray_100,
    },
    unsplash9bx5vfkxytiIcon1: {
      zIndex: 1,
      alignSelf: "stretch",
      overflow: "hidden",
    },
    cardCaption1: {
      zIndex: 2,
      paddingVertical: Padding.p_xl,
      paddingHorizontal: Padding.p_sm,
      height: 42,
      backgroundColor: Color.aliceblue,
      display: "none",
      alignItems: "center",
      flexDirection: "row",
      alignSelf: "stretch",
    },
    abstract1: {
      color: Color.mediumvioletred_200,
    },
    tagdarken4: {
      marginLeft: 8,
    },
    thereAreMany1: {
      color: Color.defaultGray500,
      height: 45,
      fontFamily: FontFamily.notoSansMalayalamUIRegular,
      marginTop: 18,
      lineHeight: 23,
      fontSize: FontSize.fontSansTextBaseSemibold_size,
      textAlign: "left",
      letterSpacing: 1,
      overflow: "hidden",
    },
    visiterLeSite1: {
      color: Color.mediumvioletred_400,
    },
    cardFooter1: {
      backgroundColor: Color.white,
      zIndex: 3,
    },
    cardChild: {
      top: 111,
      left: 7,
      zIndex: 4,
    },
    card1: {
      top: 593,
      backgroundColor: Color.dodgerblue_300,
    },
    menuAlt2OutlineIconOverlay: {
      flex: 1,
      alignItems: "flex-start",
      justifyContent: "center",
      backgroundColor: "rgba(113, 113, 113, 0.3)",
    },
    menuAlt2OutlineIconBg: {
      position: "absolute",
      width: "100%",
      height: "100%",
      left: 0,
      top: 0,
    },
    icon: {
      height: "100%",
      overflow: "hidden",
    },
    menualt2outline: {
      height: 32,
      width: 32,
    },
    stands: {
      fontSize: FontSize.size_5xl,
      color: Color.mediumvioletred_300,
      display: "flex",
      marginLeft: 18,
      textAlign: "left",
      alignItems: "center",
      alignSelf: "stretch",
      flex: 1,
    },
    iconsdarkfilter: {
      maxHeight: "100%",
      maxWidth: "100%",
      alignSelf: "stretch",
      overflow: "hidden",
      width: "100%",
      flex: 1,
    },
    iconoutlinedotsCircleHoriz: {
      width: 20,
      marginLeft: 8,
      height: 20,
    },
    iconoutlinedotsCircleHoriz1: {
      height: 16,
      marginLeft: 8,
      width: 16,
    },
    button: {
      fontSize: FontSize.fontSansTextXsSemibold_size,
      lineHeight: 16,
    },
    button1: {
      fontSize: FontSize.fontSansTextSmSemibold_size,
      lineHeight: 20,
    },
    button2: {
      lineHeight: 24,
      fontSize: FontSize.fontSansTextBaseSemibold_size,
      color: Color.customTextTooltips,
      fontFamily: FontFamily.interSemiboldItalic,
      fontStyle: "italic",
    },
    button3: {
      fontSize: FontSize.fontSansTextLgSemibold_size,
      lineHeight: 28,
    },
    iconoutlinedotsCircleHoriz4: {
      width: 24,
      height: 24,
      marginLeft: 8,
    },
    buttondarken: {
      backgroundColor: Color.gray_300,
      borderColor: "#c3136c",
      height: 30,
      width: 32,
      borderWidth: 2,
      padding: Padding.p_7xs,
      justifyContent: "center",
      borderRadius: Border.br_xs,
      borderStyle: "solid",
    },
    searchoutline: {
      marginLeft: 18,
      overflow: "hidden",
    },
    menualt2outlineParent: {
      top: 1,
      width: 390,
      height: 72,
      padding: Padding.p_xs,
      alignItems: "center",
      flexDirection: "row",
    },
    standsNancyItem: {
      top: 72,
      borderColor: "rgba(248, 110, 194, 0.5)",
      width: 391,
      height: 1,
      borderTopWidth: 1,
      borderStyle: "solid",
    },
    standsNancy: {
      flex: 1,
      backgroundColor: Color.gray_100,
    },
  });
 export const StyleStrasbourg = StyleSheet.create({
  iconLayout: {
    width: "100%",
    overflow: "hidden",
  },
  standsLayout: {
    height: 1,
    borderTopWidth: 1,
    borderStyle: "solid",
  },
  cardLayout: {
    width: 366,
    borderRadius: Border.br_xs,
    left: 12,
    position: "relative",
  },
  cardSpaceBlock4: {
    paddingVertical: Padding.p_base,
    paddingHorizontal: 0,
    backgroundColor: Color.gray_100,
  },
  textClr: {
    color: Color.mediumslateblue,
    textAlign: "left",
  },
  text2Typo: {
    fontFamily: FontFamily.notoSansMalayalamUISemibold,
    fontWeight: "600",
  },
  parentFlexBox: {
    justifyContent: "space-between",
    alignItems: "center",
    flexDirection: "row",
  },
  cardCommon: {
    display: "none",
    overflow: "hidden",
  },
  shareFlexBox: {
    marginLeft: 20,
    alignItems: "center",
    flexDirection: "row",
  },
  cardHeader1Position: {
    zIndex: 0,
    alignSelf: "stretch",
    overflow: "hidden",
  },
  childLayout: {
    height: 186,
    width: 350,
    borderColor: "#fff",
    borderWidth: 2,
    borderStyle: "solid",
    position: "absolute",
  },
  cardSpaceBlock: {
    paddingVertical: Padding.p_6xl,
    justifyContent: "center",
    paddingHorizontal: 0,
    alignSelf: "stretch",
    overflow: "hidden",
  },
  abstractTypo: {
    fontFamily: FontFamily.interMedium,
    fontWeight: "500",
    textTransform: "lowercase",
    lineHeight: 20,
  },
  tagdarkenFlexBox1: {
    paddingVertical: Padding.p_9xs,
    paddingHorizontal: Padding.p_xs,
    backgroundColor: Color.mediumslateblue,
    borderRadius: Border.br_13xl,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    overflow: "hidden",
  },
  thereSpaceBlock: {
    marginTop: 18,
    alignSelf: "stretch",
  },
  visiterSpaceBlock: {
    marginLeft: 6,
    fontFamily: FontFamily.notoSansMalayalamUIRegular,
    lineHeight: 23,
  },
  unsplash9bx5vfkxytiIconLayout: {
    height: 200,
    maxWidth: "100%",
    width: "100%",
  },
  abstract1Typo: {
    color: Color.bluePrimary,
    fontSize: FontSize.fontSansTextSmSemibold_size,
    textAlign: "left",
  },
  tagdarkenFlexBox: {
    backgroundColor: Color.lavender,
    paddingVertical: Padding.p_9xs,
    paddingHorizontal: Padding.p_xs,
    borderRadius: Border.br_13xl,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    overflow: "hidden",
  },
  standsStrasbourgItemPosition: {
    left: 0,
    position: "absolute",
  },
  buttondarkenFlexBox: {
    padding: Padding.p_7xs,
    alignItems: "center",
    flexDirection: "row",
  },
  buttonTypo: {
    color: Color.customTextTooltips,
    fontFamily: FontFamily.interSemiboldItalic,
    fontStyle: "italic",
    marginLeft: 8,
    textAlign: "center",
    display: "none",
    fontWeight: "600",
  },
  standsStrasbourgChild: {
    top: 577,
    borderColor: "rgba(171, 185, 229, 0.65)",
    width: 367,
    left: 12,
    position: "absolute",
    borderTopWidth: 1,
    borderStyle: "solid",
  },
  text1: {
    fontSize: FontSize.size_mini,
    fontFamily: FontFamily.notoSansMalayalamUIBold,
    fontWeight: "700",
  },
  text2: {
    fontSize: FontSize.fontSansTextSmSemibold_size,
  },
  text: {
    textAlign: "left",
    lineHeight: 20,
    letterSpacing: 1,
    color: Color.mediumslateblue,
  },
  likes: {
    alignItems: "center",
    flexDirection: "row",
    overflow: "hidden",
  },
  loremIpsum: {
    fontSize: FontSize.size_9xl,
    color: Color.white,
    textAlign: "left",
    flex: 1,
  },
  vectorIcon: {
    height: 20,
    width: 16,
  },
  bookmark: {
    width: 65,
    height: 50,
    paddingHorizontal: Padding.p_8xs,
    paddingVertical: Padding.p_10xs,
    justifyContent: "center",
    borderRadius: Border.br_31xl,
    alignItems: "center",
    flexDirection: "row",
    overflow: "hidden",
  },
  loremIpsumParent: {
    alignSelf: "stretch",
  },
  cardHeader: {
    alignSelf: "stretch",
    overflow: "hidden",
  },
  vectorIcon1: {
    width: 15,
    height: 18,
  },
  mapShadowBox: {
    padding: Padding.p_xl,
    shadowOpacity: 1,
    elevation: 7,
    shadowRadius: 7,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowColor: "rgba(0, 0, 0, 0.11)",
    borderRadius: Border.br_81xl,
    height: 40,
    width: 40,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    overflow: "hidden",
  },
  nStand: {
    marginLeft: 5,
    color: Color.steelblue,
    lineHeight: 23,
    fontSize: FontSize.fontSansTextBaseSemibold_size,
    fontFamily: FontFamily.notoSansMalayalamUIBold,
    fontWeight: "700",
    textAlign: "left",
    letterSpacing: 1,
  },
  liensDuStands: {
    textAlign: "center",
    color: Color.steelblue,
    fontSize: FontSize.fontSansTextBaseSemibold_size,
    fontFamily: FontFamily.notoSansMalayalamUIBold,
    fontWeight: "700",
  },
  vectorIcon2: {
    width: 19,
    height: 20,
  },
  share1: {
    padding: Padding.p_3xs,
    height: 40,
    width: 40,
    justifyContent: "center",
    borderRadius: Border.br_31xl,
    alignItems: "center",
    flexDirection: "row",
    overflow: "hidden",
  },
  share: {
    overflow: "hidden",
  },
  cardCaption: {
    paddingVertical: Padding.p_xl,
    paddingHorizontal: Padding.p_sm,
    height: 42,
    backgroundColor: Color.aliceblue,
    display: "none",
    alignItems: "center",
    flexDirection: "row",
    alignSelf: "stretch",
  },
  unsplash9bx5vfkxytiIcon: {
    height: 200,
    maxWidth: "100%",
    width: "100%",
  },
  frameChild: {
    top: 7,
    left: 8,
    zIndex: 1,
  },
  unsplash9bx5vfkxytiParent: {
    alignSelf: "stretch",
  },
  abstract: {
    color: Color.white,
    fontSize: FontSize.fontSansTextSmSemibold_size,
    textAlign: "left",
  },
  tagdarken1: {
    marginLeft: 8,
  },
  tagdarkenParent: {
    flexDirection: "row",
    alignSelf: "stretch",
  },
  thereAreMany: {
    height: 45,
    fontFamily: FontFamily.notoSansMalayalamUIRegular,
    marginTop: 18,
    lineHeight: 23,
    fontSize: FontSize.fontSansTextBaseSemibold_size,
    textAlign: "left",
    letterSpacing: 1,
    overflow: "hidden",
    color: Color.white,
  },
  iconsexternallink: {
    width: 11,
    height: 11,
    overflow: "hidden",
  },
  visiterLeSite: {
    fontSize: FontSize.fontSansTextSmSemibold_size,
    textAlign: "left",
    color: Color.mediumslateblue,
  },
  iconsexternallinkParent: {
    alignItems: "center",
    flexDirection: "row",
  },
  shareoutlineIcon: {
    width: 12,
    height: 12,
    overflow: "hidden",
  },
  frameParent: {
    justifyContent: "space-between",
    alignItems: "center",
    flexDirection: "row",
  },
  cardFooter: {
    backgroundColor: Color.gray_100,
  },
  card: {
    top: 89,
    backgroundColor: Color.dodgerblue_200,
  },
  cardHeader1: {
    paddingVertical: Padding.p_base,
    paddingHorizontal: 0,
    backgroundColor: Color.gray_100,
  },
  unsplash9bx5vfkxytiIcon1: {
    zIndex: 1,
    alignSelf: "stretch",
    overflow: "hidden",
  },
  cardCaption1: {
    zIndex: 2,
    paddingVertical: Padding.p_xl,
    paddingHorizontal: Padding.p_sm,
    height: 42,
    backgroundColor: Color.aliceblue,
    display: "none",
    alignItems: "center",
    flexDirection: "row",
    alignSelf: "stretch",
  },
  abstract1: {
    fontFamily: FontFamily.interMedium,
    fontWeight: "500",
    textTransform: "lowercase",
    lineHeight: 20,
  },
  tagdarken4: {
    marginLeft: 8,
  },
  thereAreMany1: {
    color: Color.defaultGray500,
    height: 45,
    fontFamily: FontFamily.notoSansMalayalamUIRegular,
    marginTop: 18,
    lineHeight: 23,
    fontSize: FontSize.fontSansTextBaseSemibold_size,
    textAlign: "left",
    letterSpacing: 1,
    overflow: "hidden",
  },
  visiterLeSite1: {
    marginLeft: 6,
    fontFamily: FontFamily.notoSansMalayalamUIRegular,
    lineHeight: 23,
  },
  cardFooter1: {
    backgroundColor: Color.white,
    zIndex: 3,
  },
  cardChild: {
    top: 111,
    left: 7,
    zIndex: 4,
  },
  card1: {
    top: 593,
    backgroundColor: Color.dodgerblue_300,
  },
  menuAlt2OutlineIconOverlay: {
    flex: 1,
    alignItems: "flex-start",
    justifyContent: "center",
    backgroundColor: "rgba(113, 113, 113, 0.3)",
  },
  menuAlt2OutlineIconBg: {
    position: "absolute",
    width: "100%",
    height: "100%",
    left: 0,
    top: 0,
  },
  icon: {
    height: "100%",
    overflow: "hidden",
  },
  menualt2outline: {
    height: 32,
    width: 32,
  },
  stands: {
    fontSize: FontSize.size_5xl,
    color: Color.lightsteelblue_100,
    display: "flex",
    marginLeft: 18,
    textAlign: "left",
    alignItems: "center",
    alignSelf: "stretch",
    flex: 1,
  },
  iconsdarkfilter: {
    maxHeight: "100%",
    maxWidth: "100%",
    alignSelf: "stretch",
    overflow: "hidden",
    width: "100%",
    flex: 1,
  },
  iconoutlinedotsCircleHoriz: {
    width: 20,
    marginLeft: 8,
    height: 20,
  },
  iconoutlinedotsCircleHoriz1: {
    height: 16,
    marginLeft: 8,
    width: 16,
  },
  button: {
    fontSize: FontSize.fontSansTextXsSemibold_size,
    lineHeight: 16,
  },
  button1: {
    fontSize: FontSize.fontSansTextSmSemibold_size,
    lineHeight: 20,
  },
  button2: {
    lineHeight: 24,
    fontSize: FontSize.fontSansTextBaseSemibold_size,
    color: Color.customTextTooltips,
    fontFamily: FontFamily.interSemiboldItalic,
    fontStyle: "italic",
  },
  button3: {
    fontSize: FontSize.fontSansTextLgSemibold_size,
    lineHeight: 28,
  },
  iconoutlinedotsCircleHoriz4: {
    width: 24,
    height: 24,
    marginLeft: 8,
  },
  buttondarken: {
    backgroundColor: Color.gray_300,
    borderColor: "#abb9e5",
    height: 30,
    width: 32,
    borderWidth: 2,
    padding: Padding.p_7xs,
    justifyContent: "center",
    borderRadius: Border.br_xs,
    borderStyle: "solid",
  },
  searchoutline: {
    marginLeft: 18,
    overflow: "hidden",
  },
  menualt2outlineParent: {
    top: 1,
    width: 390,
    height: 72,
    padding: Padding.p_xs,
    alignItems: "center",
    flexDirection: "row",
  },
  standsStrasbourgItem: {
    top: 72,
    borderColor: "rgba(171, 185, 229, 0.5)",
    width: 391,
    height: 1,
    borderTopWidth: 1,
    borderStyle: "solid",
  },
  standsStrasbourg: {
    flex: 1,
  
    backgroundColor: Color.gray_100,
  },
});
